title:  'Implicit Neural Field-Based Process Planning for Multi-Axis Manufacturing: Direct Control over Collision Avoidance and Toolpath Geometry'
description: 'Implicit Neural Field-Based Process Planning for Multi-Axis Manufacturing: Direct Control over Collision Avoidance and Toolpath Geometry. Neelotpal Dutta, Tianyu Zhang, Tao Liu, Yongxue Chen, Charlie C.L. Wang'	
theme: jekyll-theme-cayman
