title: "Implicit Neural Field-Based Process Planning for Multi-Axis Manufacturing: Direct Control over Collision Avoidance and Toolpath Geometry"
description: 'Neelotpal Dutta, Tianyu Zhang, Tao Liu, Yongxue Chen, Charlie C.L. Wang. <br> Digital Manufacturing Lab, University of Manchester'
google_analytics: G-07BGR3LPXZ
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
