"""Common checkpoint, loss-log, timing-log, and progress helpers."""

import os
import time

import numpy as np
import torch

try:
    from tqdm.auto import tqdm
except ImportError:
    tqdm = None


LOSS_KEYS = (
    "total",
    "layer",
    "toolpath",
    "stress",
    "cross",
    "collision",
    "base",
    "boundary",
    "platform",
)


def output_root(config):
    """Return the root folder for all outputs generated by one config."""
    return config.output_dir or os.path.join("outputs", config.model_name or "run")


def checkpoint_dir(config):
    return config.checkpoint_dir or os.path.join(output_root(config), "checkpoints")


def loss_log_dir(config):
    return config.loss_log_dir or os.path.join(output_root(config), "losses")


def ensure_output_dirs(config):
    """Create output folders before writing logs or checkpoints."""
    os.makedirs(checkpoint_dir(config), exist_ok=True)
    os.makedirs(loss_log_dir(config), exist_ok=True)


def init_loss_records():
    """Create a common loss-record dictionary for all workflows."""
    return {key: [] for key in LOSS_KEYS}


def zero_like_loss(reference):
    return reference.detach() * 0.0


def init_batch_losses(reference):
    """Create independent zero tensors matching the current loss tensor."""
    zero = zero_like_loss(reference)
    return {key: zero.clone() for key in LOSS_KEYS}


def to_record_value(value, iter_count):
    if iter_count < 1:
        return 0
    if torch.is_tensor(value):
        averaged = value.detach().to("cpu") / iter_count
        if averaged.numel() == 1:
            return float(averaged.item())
        return averaged.numpy()
    return value


def append_loss_records(records, batch_losses, iter_count):
    """Append per-epoch averaged loss values to the log dictionary."""
    for key in LOSS_KEYS:
        records[key].append(to_record_value(batch_losses.get(key, 0), iter_count))


def write_loss_logs(config, records):
    """Write each loss bucket to its own text file."""
    ensure_output_dirs(config)
    for key, values in records.items():
        np.savetxt(os.path.join(loss_log_dir(config), f"loss_{key}.txt"), np.array(values))


def write_timing_log(config, epoch, start_time):
    """Append elapsed training time for a saved checkpoint epoch."""
    ensure_output_dirs(config)
    path = os.path.join(loss_log_dir(config), config.timing_log_name)
    elapsed = time.time() - start_time
    with open(path, "a") as file:
        file.write(f"{epoch} {elapsed:.6f}\n")


def save_checkpoint_bundle(config, epoch, checkpoint_items):
    """Save one checkpoint file per trainable component."""
    ensure_output_dirs(config)
    prefix = config.checkpoint_prefix or (config.model_name or "model")
    for name, item in checkpoint_items.items():
        path = os.path.join(checkpoint_dir(config), f"{prefix}_{name}_epoch_{epoch:05d}.pt")
        torch.save({"model_state_dict": item.state_dict()}, path)


class TextProgress:
    """Plain-text fallback when tqdm is unavailable or not visible."""

    def __init__(self, epochs, config):
        self.epochs = epochs
        self.config = config
        self.current_epoch = None
        self.label = config.progress_label or config.model_name or "training"
        self.total_epochs = max(config.epoch_count - 1, 1)
        self.every = max(1, config.progress_every_epochs)

    def __iter__(self):
        for epoch in self.epochs:
            self.current_epoch = epoch
            yield epoch

    def set_postfix(self, values):
        if self.current_epoch is None:
            return
        should_print = self.current_epoch == 1
        should_print = should_print or self.current_epoch % self.every == 0
        should_print = should_print or self.current_epoch >= self.total_epochs
        if not should_print:
            return

        suffix = " ".join(f"{key}={value:.6g}" if isinstance(value, float) else f"{key}={value}" for key, value in values.items())
        print(f"{self.label}: epoch {self.current_epoch}/{self.total_epochs} {suffix}")


def epoch_progress(config):
    """Return either a tqdm iterator, text-progress iterator, or plain range."""
    epochs = range(1, config.epoch_count)
    if not config.show_progress:
        return epochs
    if tqdm is None:
        return TextProgress(epochs, config)
    return tqdm(epochs, desc=config.progress_label or config.model_name or "training", mininterval=1.0)


def update_progress(progress, values):
    """Update tqdm postfix or print a text progress line."""
    if hasattr(progress, "set_postfix"):
        clean_values = {}
        for key, value in values.items():
            if torch.is_tensor(value) and value.numel() == 1:
                value = float(value.detach().to("cpu").item())
            clean_values[key] = value
        progress.set_postfix(clean_values)
