"""Common checkpoint, loss-log, timing-log, and progress helpers."""

from __future__ import annotations

import time
from collections.abc import Iterable
from pathlib import Path

import numpy as np
import torch
from tqdm.auto import tqdm

LOSS_KEYS: tuple[str, ...] = (
    "total",
    "layer",
    "toolpath",
    "stress",
    "cross",
    "collision",
    "base",
    "boundary",
    "platform",
)


def output_root(config) -> Path:
    """Root folder for all outputs generated by one config."""
    return Path(config.output_dir or Path("outputs") / (config.model_name or "run"))


def checkpoint_dir(config) -> Path:
    return Path(config.checkpoint_dir or output_root(config) / "checkpoints")


def loss_log_dir(config) -> Path:
    return Path(config.loss_log_dir or output_root(config) / "losses")


def ensure_output_dirs(config) -> None:
    """Create output folders before writing logs or checkpoints."""
    checkpoint_dir(config).mkdir(parents=True, exist_ok=True)
    loss_log_dir(config).mkdir(parents=True, exist_ok=True)


def init_loss_records() -> dict[str, list]:
    """Per-epoch loss-record dictionary, one entry per LOSS_KEYS bucket."""
    return {key: [] for key in LOSS_KEYS}


def zero_like_loss(reference: torch.Tensor) -> torch.Tensor:
    return reference.detach() * 0.0


def init_batch_losses(reference: torch.Tensor) -> dict[str, torch.Tensor]:
    """Independent zero tensors matching the current loss tensor."""
    zero = zero_like_loss(reference)
    return {key: zero.clone() for key in LOSS_KEYS}


def to_record_value(value, iter_count: int):
    if iter_count < 1:
        return 0
    if torch.is_tensor(value):
        averaged = value.detach().to("cpu") / iter_count
        if averaged.numel() == 1:
            return float(averaged.item())
        return averaged.numpy()
    return value


def append_loss_records(records: dict[str, list], batch_losses: dict[str, torch.Tensor], iter_count: int) -> None:
    """Append per-epoch averaged loss values to the log dictionary."""
    for key in LOSS_KEYS:
        records[key].append(to_record_value(batch_losses.get(key, 0), iter_count))


def write_loss_logs(config, records: dict[str, list]) -> None:
    """Write each loss bucket to its own text file."""
    ensure_output_dirs(config)
    out_dir = loss_log_dir(config)
    for key, values in records.items():
        np.savetxt(out_dir / f"loss_{key}.txt", np.array(values))


def write_timing_log(config, epoch: int, start_time: float) -> None:
    """Append elapsed training time for a saved checkpoint epoch."""
    ensure_output_dirs(config)
    path = loss_log_dir(config) / config.timing_log_name
    elapsed = time.time() - start_time
    with open(path, "a") as file:
        file.write(f"{epoch} {elapsed:.6f}\n")


def save_checkpoint_bundle(config, epoch: int, checkpoint_items: dict[str, torch.nn.Module]) -> None:
    """Save one checkpoint file per trainable component."""
    ensure_output_dirs(config)
    prefix = config.checkpoint_prefix or (config.model_name or "model")
    out_dir = checkpoint_dir(config)
    for name, item in checkpoint_items.items():
        path = out_dir / f"{prefix}_{name}_epoch_{epoch:05d}.pt"
        torch.save({"model_state_dict": item.state_dict()}, path)


class TextProgress:
    """Plain-text alternative to tqdm; used when ``config.show_progress`` is
    True but a tqdm display would not render (no TTY, headless run)."""

    def __init__(self, epochs: Iterable[int], config) -> None:
        self.epochs = epochs
        self.config = config
        self.current_epoch: int | None = None
        self.label = config.progress_label or config.model_name or "training"
        self.total_epochs = max(config.epoch_count - 1, 1)
        self.every = max(1, config.progress_every_epochs)

    def __iter__(self):
        for epoch in self.epochs:
            self.current_epoch = epoch
            yield epoch

    def set_postfix(self, values: dict) -> None:
        if self.current_epoch is None:
            return
        should_print = (
            self.current_epoch == 1 or self.current_epoch % self.every == 0 or self.current_epoch >= self.total_epochs
        )
        if not should_print:
            return

        suffix = " ".join(
            f"{key}={value:.6g}" if isinstance(value, float) else f"{key}={value}" for key, value in values.items()
        )
        print(f"{self.label}: epoch {self.current_epoch}/{self.total_epochs} {suffix}")


def epoch_progress(config):
    """Return a tqdm iterator, a text-progress iterator, or a plain range.

    Selection is based on ``config.show_progress``; the tqdm form is used
    unconditionally when progress is requested, because tqdm is a hard
    dependency.
    """
    epochs = range(1, config.epoch_count)
    if not config.show_progress:
        return epochs
    if hasattr(config, "use_text_progress") and config.use_text_progress:
        return TextProgress(epochs, config)
    return tqdm(epochs, desc=config.progress_label or config.model_name or "training", mininterval=1.0)


def update_progress(progress, values: dict) -> None:
    """Update tqdm postfix or print a text progress line."""
    if hasattr(progress, "set_postfix"):
        clean_values = {}
        for key, value in values.items():
            if torch.is_tensor(value) and value.numel() == 1:
                value = float(value.detach().to("cpu").item())
            clean_values[key] = value
        progress.set_postfix(clean_values)
